name: Deploy to Dreamhost

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Prepare temp directory on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            # remove any leftover temp and recreate
            rm -rf /home/dh_jirb5e/vittoretti.com_shopify_sync_app_tmp
            mkdir -p /home/dh_jirb5e/vittoretti.com_shopify_sync_app_tmp

      - name: Upload static files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "dist/"
          target: "/home/dh_jirb5e/vittoretti.com_shopify_sync_app_tmp"

      - name: Swap temp into place and clean up
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          script: |
            # ensure target folder exists
            mkdir -p /home/dh_jirb5e/vittoretti.com/shopify_sync

            # rename current app to .old for rollback
            mv /home/dh_jirb5e/vittoretti.com/shopify_sync/app /home/dh_jirb5e/vittoretti.com/shopify_sync/app_old 2>/dev/null || true

            # move new build into place
            mv /home/dh_jirb5e/vittoretti.com_shopify_sync_app_tmp/dist /home/dh_jirb5e/vittoretti.com/shopify_sync/app

            # remove the old backup
            rm -rf /home/dh_jirb5e/vittoretti.com/shopify_sync/app_old

            # remove the temp directory
            rm -rf /home/dh_jirb5e/vittoretti.com_shopify_sync_app_tmp